# Generated by Django 5.2.16 on 2026-07-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
