# Generated by Django 5.2.16 on 2026-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
